
#ifndef _LIVE_P2PCOMMON2_BASE_SYNACAST_PROTOCOL_NAT_H_
#define _LIVE_P2PCOMMON2_BASE_SYNACAST_PROTOCOL_NAT_H_


enum MY_STUN_NAT_TYPE
{
	STUN_TYPE_INVALID = 0, 
	STUN_TYPE_ERROR = 1, 
	STUN_TYPE_PUBLIC = 2, 
	STUN_TYPE_FULLCONENAT = 3, 
	STUN_TYPE_IP_RESTRICTEDNAT = 4, 
	STUN_TYPE_IP_PORT_RESTRICTEDNAT = 5,
	STUN_TYPE_SYMNAT = 6, 
};


/*
enum MY_STUN_NAT_TYPE
{
TYPE_ERROR = -1,
TYPE_FULLCONENAT = 0,	
TYPE_IP_RESTRICTEDNAT,
TYPE_IP_PORT_RESTRICTEDNAT,
TYPE_SYMNAT,
TYPE_PUBLIC
};
*/


#endif